"""Initial migration.

Revision ID: a610a0a9ade1
Revises: e7efe22c8655
Create Date: 2024-10-08 10:25:23.198807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a610a0a9ade1'
down_revision = 'e7efe22c8655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_super_admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('pin', sa.String(length=6), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('pin')
        batch_op.drop_column('is_super_admin')

    # ### end Alembic commands ###
