"""Add birthday column to User model

Revision ID: e7efe22c8655
Revises: 12bdfa313c3c
Create Date: 2024-10-07 13:45:35.263644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7efe22c8655'
down_revision = '12bdfa313c3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthday', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('birthday')

    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
